# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-21 03:38
from __future__ import unicode_literals

try:
    from django.contrib.auth.validators import UnicodeUsernameValidator
except ImportError:  # pragma: no cover -  pre Django 1.10 compatibility
    from django.core.validators import (
        RegexValidator as UnicodeUsernameValidator
    )  # pragma: no cover -  pre Django 1.10 compatibility
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('simpleuser', '0002_managed_metadata_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={
                    'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits'
                          ' and @/./+/-/_ only.',
                max_length=150, unique=True,
                validators=[UnicodeUsernameValidator()],
                verbose_name='username'),
        ),
    ]
